### ISSUE TITLE
In Ruby 2.1.1 / Rails 4.1.1 the route must be defined manually

### ISSUE THREAD

**Issue by itsjms** [igorkasyanchuk/rails_db#10]
In Ruby 2.1.1 / Rails 4.1.1 to get the route working properly I had to turn the `config.automatic_routes_mount` to `false` and manually add `mount RailsDb::Engine => "/rails/db", as: 'rails_db'` as a route in my application.

**Comment by igorkasyanchuk** [comment]
BTW for people who don't know - you need to generate config

`rails g initializer rails_db`

And then edit config/initializers/rails_db.rb and restart app

**Comment by igorkasyanchuk** [comment]
gem 'rails', '4.1.1'
gem 'rails_db'
gem 'sass', '>= 3.3.14'
gem 'sass-rails', '>= 5.0.0'
gem 'foundation-rails', '>= 5.5.0.0'

Everything works well (automatic routes mounting I mean works correctly)
