### ISSUE TITLE
undefined method current_user

### ISSUE THREAD

**Issue by chabgood** [igorkasyanchuk/rails_db#102]
Rails 5, getting:

`undefined method `current_user' for #<RailsDb::DashboardController:0x00007fad37cfb188>`
when I do `config.verify_access_proc = proc { |controller| controller.current_user.system_admin? }`

**Comment by igorkasyanchuk** [comment]
This is just an example. Do you use any authentication library like devise? You can add to own logic to block access to rails db.

**Comment by chabgood** [comment]
We do not use devise.

**Comment by igorkasyanchuk** [comment]
So just change logic in this block. Inside you have access to controller and could call your own verification methods

**Comment by chabgood** [comment]
since this is loaded up when rails starts how can i put in logic to see who the user is?

**Comment by igorkasyanchuk** [comment]
1. comment this line if you don't need http://prntscr.com/pah2ye
2. or change an appropriate logic, I don't know how you can check permissions, but you have access to controller and could implement all logic in this proc.

**Comment by chabgood** [comment]
I can do current_user from a controller, this is still giving me the same error.  Is there a way to mix in current_user at a different time so it works?

**Comment by igorkasyanchuk** [comment]
What is your config/initializers/rails_db.rb? Paste it
