### ISSUE TITLE
Remove folder that seems not needed in the gem

### ISSUE THREAD

**Issue by ekremkaraca** [igorkasyanchuk/rails_db#104]
Hi,

I've recognized that the size of your latest gem is about 3.4 MiB. When it is installed to local machine, its size is 11.7 MiB. Here are your files after installation:

```
    7.4 MiB [##########] /test                                                                                            
    4.1 MiB [#####     ] /app
  172.0 KiB [          ] /lib
   40.0 KiB [          ] /config
   16.0 KiB [          ] /bin
    8.0 KiB [          ]  Gemfile.lock
    4.0 KiB [          ]  rails_db.gemspec
    4.0 KiB [          ]  MIT-LICENSE
    4.0 KiB [          ]  Rakefile
    4.0 KiB [          ]  Gemfile

```
Since `test` folder is not needed in the gem, it would be nice if it is removed.

**Comment by igorkasyanchuk** [comment]
This folder contains "standalone" Rails app which can be used: https://github.com/igorkasyanchuk/rails_db#railsdb-standalone

I think size if not a major problem

**Comment by ekremkaraca** [comment]
- I install the gem
- During installation, files packed in the gem were extracted
- Can you tell me how I use `test` folder in a Rails app (unless I am testing the gem, not a Rails app; if I test it, would it be better to download entire source code?)
- should the gem be tested after it's released in a Rails app, so we need tests?

**Comment by igorkasyanchuk** [comment]
To test gem - clone repo, and run rake test.
I have section in Readme how to test gem.

**Comment by ekremkaraca** [comment]
Ok, sorry for disturbing.

**Comment by ekremkaraca** [comment]
Hi again, I see you've updated the gem. Now I just wonder what's the purpose to include cache files (more than 1400) in your gem as they appear below:

PS: GitHub warned me not to add whole log so I've pasted link below:

https://gist.github.com/ekremkaraca/95ec6e420b0e6ed339b16609960df1d0

**Comment by igorkasyanchuk** [comment]
@ekremkaraca could you please create a PR
and clear, and add to gitignore
rails_db-2.2.0/test/dummy/tmp/cache folder

test/dummy in general is needed, because it's used in standalone app. But cache is not

**Comment by ekremkaraca** [comment]
Yep, I did it with #112 & #113.

**Comment by igorkasyanchuk** [comment]
try version 2.1.1
I'm deleting some not needed folders before a new release

**Comment by igorkasyanchuk** [comment]
oh 2.2.1
