### ISSUE TITLE
Ransack latest version is breaking this gem

### ISSUE THREAD

**Issue by kapso** [igorkasyanchuk/rails_db#114]
The latest version of ransack `2.3.2` is causing the following error -

```
/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rails_db-2.2.1/lib/ext/ransack_ext.rb:18:in `alias_method': undefined method `url_options' for class `Ransack::Helpers::FormHelper::SortLink' (NameError)
```

**Comment by igorkasyanchuk** [comment]
@kapso can you try to fix this issue?

**Comment by kapso** [comment]
Hey @igorkasyanchuk I will give this a shot over the weekend. Thanks.

**Comment by saberprashant** [comment]
Can anyone help me with this please :)
I am getting this error:
```
.rvm/gems/ruby-2.6.3/gems/rails_db-2.1.0/lib/ext/ransack_ext.rb:18:in `alias_method': undefined method `url_options' for class `Ransack::Helpers::FormHelper::SortLink' (NameError)
```

**Comment by igorkasyanchuk** [comment]
guys come on, you using open-source gems and not willing to contribute and fix the issue

**Comment by igorkasyanchuk** [comment]
try this branch and let me know if it works https://github.com/igorkasyanchuk/rails_db/pull/115

**Comment by igorkasyanchuk** [comment]
version 2.3.0 has fix for the latest ransack
