### ISSUE TITLE
Manually adding a user issue

### ISSUE THREAD

**Issue by daveit** [igorkasyanchuk/rails_db#125]
When I try to add a new user manually (this is a requirement for a particular application) It does not save.
I have in the past had to keep trying, it seems to save when I have certain fields entered.
This is for devise users
TIA, Dave
ps - I use this site for the password:
https://www.browserling.com/tools/bcrypt
Which does not seem to be the issue, when it does save after fiddling around, the password is correct!

**Comment by igorkasyanchuk** [comment]
@daveit I think the best is to fork gem and connect in your app and debug line where it storing and why not creating. 
I assume it is might happen because of some logic for an some field in DB which is generated in model.

**Comment by daveit** [comment]
Thanks for getting back - no problems at all - new users are added very rarely, and I can get around it - it was more as feedback.
Best regards, Dave
