### ISSUE TITLE
uninitialised constant Sass::Script (NameError)

### ISSUE THREAD

**Issue by bublik42** [igorkasyanchuk/rails_db#13]
>uninitialised constant Sass::Script (NameError) 

The error appeared after I installed rails_db gem. Rails_db's dependencies versions are:

foundation-rails (5.5.3.2)
sass (3.4.19)
sass-rails (5.0.4)
codemirror-rails (5.6)
font-awesome-rails (3.2.1.0)
jquery-rails (= 4.0.4)
rails (4.2.1)

**Comment by igorkasyanchuk** [comment]
Demo app: https://www.dropbox.com/s/tbtaq40pgpzd537/demo_rails_db_rails_4_2_1.zip?dl=0 works well.

Also maybe this is an issue: https://github.com/rails/sass-rails/issues/315 (and solution)

Pls next time put a stack trace of error

**Comment by igorkasyanchuk** [comment]
Let me know if issue is resovled

**Comment by bublik42** [comment]
I had to require sass gem explicitly before sass-rails as described in the issue you linked. After that I had to upgrade haml gem (3.1.7 -> 4.0.7), font-awesome-rails gem (3.2.1.0 -> 4.4.0.0).
After that rails_db works normally. It may be a good reason to make dependencies in gemfile more specific.
Thank you for the brief response.

**Comment by igorkasyanchuk** [comment]
I know, but I don't know what versions of gems working with rails_db (difficult to verify all), easier to let people help me with that, and just create list of issues and solutions how to fix them

**Comment by igorkasyanchuk** [comment]
Fixed in latest version of gem.
please don't forget to share gem with friends :)
