### ISSUE TITLE
Ransack 4.0 has breaking change

### ISSUE THREAD

**Issue by ykamin-booth** [igorkasyanchuk/rails_db#131]
FYI, [this PR](https://github.com/activerecord-hackery/ransack/pull/1400) which just got pulled into Ransack 4.0 has a breaking change for rails_db, requiring an explicit allowlist for every attribute that it's allowed to search over. I reverted my ransack version for now but it's worth thinking about how to handle this.

**Comment by igorkasyanchuk** [comment]
@ykamin-booth can you make a PR and just allow all attributes?

**Comment by igorkasyanchuk** [comment]
should work
