### ISSUE TITLE
Search doesn't work under Rails 7.1.0rc

### ISSUE THREAD

**Issue by heroturtle** [igorkasyanchuk/rails_db#134]
After upgrading to Rails 7.1.0rc, the search in my application doesn't work anymore. I get the following message:
AbstractController::ActionNotFound (The search action could not be found for the :find_table
callback on RailsDb::TablesController, but it is listed in the controller's
:only option.

**Comment by igorkasyanchuk** [comment]
I'll appreciate a PR with fix for this issue. Can you try to create ir?

**Comment by bpurinton** [comment]
I am having the same issue with `Rails 7.1.3.3`

I can reach `/rails/db`, but trying to click into any of the tables results in this in the server log:

```
AbstractController::ActionNotFound - The search action could not be found for the :find_table
callback on RailsDb::TablesController, but it is listed in the controller's
:only option.
Raising for missing callback actions is a new default in Rails 7.1, if you'd
like to turn this off you can delete the option from the environment configurations
or set `config.action_controller.raise_on_missing_callback_actions` to `false`.:
```

So it seems that the new "missing callbacks" default in Rails 7.1 is to blame here.
