### ISSUE TITLE
Add indexes info for tables

### ISSUE THREAD

**Issue by losadaem** [igorkasyanchuk/rails_db#17]
Show this info somewhere can be useful.

 I've made already a quick implementation. If you want I can make a pull request or I let you implement it in your own way.

Right now it looks like this.

![capture d ecran 2015-10-28 a 11 20 15](https://cloud.githubusercontent.com/assets/5043618/10793228/525b8ade-7d66-11e5-8324-328ba3b06bcd.png)

**Comment by igorkasyanchuk** [comment]
Actually this task is completed in another branch https://github.com/igorkasyanchuk/rails_db/pull/14/files
I plan to release this feature tomorrow I think, I just want to spend some time to verify all again and finish deleting records.
but thanks for investigation :)
looks forward to see more ideas from you

**Comment by losadaem** [comment]
Nice! I'm going to check that branch

**Comment by igorkasyanchuk** [comment]
Yes, please, let me know how it works for you

**Comment by igorkasyanchuk** [comment]
merged to master, version 0.6
