### ISSUE TITLE
Don't force install of unused RDBMSs (mysql)

### ISSUE THREAD

**Issue by david-a-wheeler** [igorkasyanchuk/rails_db#24]
rails_db looks really cool!  However, when I install the gem, it fails & forces me to install mysql through the system package manager, even though we never use that in our application.  It shouldn't force me install things I don't use; in our case we *only* use sqlite in development and Postgres in production (and I plan to use rails_db *only* in development).
Can you trim down the dependencies so that you don't have to install mysql when you don't use it?
Thanks!

**Comment by igorkasyanchuk** [comment]
Hi David, yes, you right, I plan to remove this dependency soon

**Comment by david-a-wheeler** [comment]
On November 3, 2015 4:33:15 AM EST, Igor Kasyanchuk <notifications@github.com> wrote:
>Hi David, yes, you right, I plan to remove this dependency soon
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/igorkasyanchuk/rails_db/issues/24#issuecomment-153298046

Excellent. Thanks for the gem, it really is neat.  Once you have that I intend to add it to my project dependencies for development.
--- David A.Wheeler

**Comment by mikek68** [comment]
Same with the Postgres dependency.  I do not, nor will I be, use postgres in any of my current projects.

`checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***`

**Comment by igorkasyanchuk** [comment]
yes, I know
It's going to be solved soon, I think I've already code in master branch with fix, or on my computer, just need to test it

**Comment by igorkasyanchuk** [comment]
@mikek68 , @david-a-wheeler please try now and let me know how it works for you (version 0.7.1)

**Comment by mikek68** [comment]
@igorkasyanchuk gem install was successful, however, upon navigating to http://localhost:3000/rails/db, I received the following error:

`wrong number of arguments (1 for 2) for `asset-url'
  (in /Users/[my user name]/.rvm/gems/ruby-2.1.5@lcl_reservations/gems/rails_db-0.7.1/app/assets/stylesheets/rails_db/app.css.scss)`

I don not know if that is a result of my environment, or if there is something else that needs to be done to include the necessary assets.  I did not generate the initializer file as I did not need to modify any default settings.

**Comment by igorkasyanchuk** [comment]
maybe this is a solution https://github.com/Compass/compass-rails/issues/155 ?

**Comment by mikek68** [comment]
Although I am not using compass, I will take a look at the issue as it pertains to sass-rails.  Thank you.

**Comment by igorkasyanchuk** [comment]
but maybe issue because of old version of sass, sass-rails gem?
mine are:
    sass (3.4.19)
    sass-rails (5.0.4)

**Comment by mikek68** [comment]
Yes, that is what I am looking at as well.

**Comment by mikek68** [comment]
I am using rails 3.2, not 4.0.  Those versions only appear to be available to rails 4.0.

**Comment by igorkasyanchuk** [comment]
try to run "bundle update sass" or "bundle update sass-rails" ... something
like that
I've never tested it with Rails 3.2, I just have an automated tests and
they are passed, but this is maybe assets were not precompiled.
let me know later which versions works for you.

**Comment by paulanunda** [comment]
Thanks for the quick turnaround on this @igorkasyanchuk

**Comment by david-a-wheeler** [comment]
@igorkasyanchuk - that was fast!  I tried out version 0.7.1 and it seems to work perfectly on ruby 2.2.2, rails 4.2.4, and sqlite3 version 1.3.11.

Thanks so much!  I'm adding this to my dev environment.
