### ISSUE TITLE
Consider removing dependency on therubyracer (which depends on libv8)

### ISSUE THREAD

**Issue by david-a-wheeler** [igorkasyanchuk/rails_db#25]
The rails_db gem currently depends on therubyracer, which in turns depends on libv8.  However, libv8 either loads big precreated binaries or tries to recompile a large system.  That's extremely heavy.  Can the dependency on therubyracer be removed?

Here's my rationale.  I'm developing some open source software using Ruby on Rails.  Since I want others to collaborate with me, it's *very* important to me that others can quickly recreate the same development environment that I have using Gemfile.lock, even if they have different underlying systems.  I'm happy to have highly-functional development environments, e.g., one with a /rails/db capability.  However, gems with large binaries (like libv8) greatly increase the risk that others won't be able to recreate my development environment, because the binary and/or recompilation may fail.  There's also the risk that it's subverted (I see no evidence that libv8 is trying to be reproduceable, so it's hard for anyone to check it).  For me, this dependency on rubyracer (which depends on v8) is much less than ideal.

**Comment by igorkasyanchuk** [comment]
@david-a-wheeler please try again, with version 0.7.2, looks like without 'therubyracer' everything works well. Please test and let me know.

**Comment by david-a-wheeler** [comment]
Works like a charm!  Thanks so much.  I'm adding rails_db to the development environment of https://github.com/linuxfoundation/cii-best-practices-badge
