### ISSUE TITLE
Sidebar trouble with screen width between  640 and 1024

### ISSUE THREAD

**Issue by olegantonyan** [igorkasyanchuk/rails_db#32]
See the screenshot: http://s29.postimg.org/bereptdvb/snapshot9.png
Notice that sidebar went down and became invisible, you can't see the menu items, but you can click on them. Only when width is between 640 and 1024.
Tested in Firefox and Chromium.

**Comment by igorkasyanchuk** [comment]
Yes, you right, app was not nested on such small resolutions. Probably you can try to make a fix and send PR ?

**Comment by olegantonyan** [comment]
I think it will be a nice reason to learn foundation framework a little bit :) So I'll try
