### ISSUE TITLE
Is I18n/Internationalisation welcomed?

### ISSUE THREAD

**Issue by sashaegorov** [igorkasyanchuk/rails_db#33]
Is some body interested in I18n of this gem? I'd like to do it.

**Comment by igorkasyanchuk** [comment]
yes, I18n is something what was planned to be implemented. If you can handle this it would be great, at least start with English and Russian, and future translations will be implemented by other people.

**Comment by sashaegorov** [comment]
Ok, I'll start implementation soon. Thanks!
