### ISSUE TITLE
Simple Form if I use it in production

### ISSUE THREAD

**Issue by FlowerWrong** [igorkasyanchuk/rails_db#34]
When I use `rails_db` in production, there is a warn.
> [Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.

**Comment by igorkasyanchuk** [comment]
yes, it's expected, I didn't generated initializer because I don't want to override it if it's exists in app itself. SimpleForm will use default settings

**Comment by FlowerWrong** [comment]
@igorkasyanchuk But I did not use it. :disappointed:

**Comment by igorkasyanchuk** [comment]
But this gem using
