### ISSUE TITLE
undefined method 'per' when loading datatable

### ISSUE THREAD

**Issue by edwallitt** [igorkasyanchuk/rails_db#43]
Great gem, looking forward to using it.

Having some difficulty however viewing datatables when clicking on a table in the dashboard (from left column). Running ruby 2.2.1 and rails 4.2.4 with Ransack 1.7.0

Following error is shown in the console

``NoMethodError - undefined method `per' for #<#<Class:0x007fc78c11d810>:0x007fc78c12d418>:``

Any ideas? Could it be a Ransack compatibility issue?

Cheers

**Comment by igorkasyanchuk** [comment]
thanks for creating issue
@bbenezech could you please investigate this issue? I won't be available to do it in next 2 days or @edwallitt if you can find a solution just make a PR

**Comment by edwallitt** [comment]
Thanks @igorkasyanchuk and @bbenezech . I think it may be a compatibility issue with will_paginate. Commenting out the gem I am using (will_paginate 3.0.7).

I imagine that it will be fairly common occurrence for developer's to be using will_paginate so might be worth investigating a fix or mentioning in the docs.

**Comment by igorkasyanchuk** [comment]
@edwallitt please post full stack-trace or error, because I tried to add will_paginate (3.0.7) in dummy app and everything works. On which step it doesn't work?

**Comment by igorkasyanchuk** [comment]
actually I was able to reproduce this issue

**Comment by igorkasyanchuk** [comment]
could you please try this branch https://github.com/igorkasyanchuk/rails_db/tree/will_paginate_fix and see if it works for you?

**Comment by edwallitt** [comment]
Yes it most certainly does. Great work, and very clever solution.

**Comment by igorkasyanchuk** [comment]
version 1.1.1 with fix is pushed to rubygems
