### ISSUE TITLE
Blacklist columns?

### ISSUE THREAD

**Issue by mrudult** [igorkasyanchuk/rails_db#45]
Is there a way where I can blacklist certain columns from all tables? Like `created_at` & `updated_at`?

Blacklisting at individual table level will also be a good feature.

**Comment by igorkasyanchuk** [comment]
Right now no. You can hide them with Filter per table.

If you can make a PR for this it would be great. At least for global level

**Comment by bbenezech** [comment]
@mrudult if you really need to configure columns, you'll get a lot more leeway with `RailsAdmin`/`ActiveAdmin`/`Administrate` (in no particular order). This gem has a more `phpMyAdmin` approach.
Feel free to open a PR for a blacklist strategy on a global level (no per-model configuration, filters are stored in browser already).
