### ISSUE TITLE
STI custom inheritance_column not taken into account

### ISSUE THREAD

**Issue by dlupu** [igorkasyanchuk/rails_db#49]
I've just came across this error when trying to access a database that uses the STI mechanism. 

> The single-table inheritance mechanism failed to locate the subclass: 'bid'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite .inheritance_column to use another column for that information.

We're already using [.inheritance_column=](http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-inheritance_column-3D) in our model, so I guess the rails_db does not take into account that.

WDYT?

**Comment by igorkasyanchuk** [comment]
@dlupu please post your schema, or try to create branch with error and we may try to fix it together

**Comment by igorkasyanchuk** [comment]
try now with latest version
