### ISSUE TITLE
font-awesome gem clash

### ISSUE THREAD

**Issue by mkhairi** [igorkasyanchuk/rails_db#5]
i'm using official font-aweseome gem ```gem 'font-awesome-sass'```. look like it has been override load with rails_db dependency ```gem 'font-awesome-rails'``` how to avoid this?

**Comment by igorkasyanchuk** [comment]
what exactly not works?
BTW `font-awesome-rails` is more popular based on stars number on github

**Comment by mkhairi** [comment]
Can't deny on that popularity. ```font-awesome-rails``` now already 4 years old  while ```font-awesome-sass``` born 2 years ago.
Just a small issue here, i can't extend or override font-awesome variable. that all.

**Comment by igorkasyanchuk** [comment]
How this clash looks?  I want to understand better the error. Please provide more details. Thanks

**Comment by mkhairi** [comment]
technically both gem use the same name require css/sass ```*= require font-awesome``` or ```@import "font-awesome"; ``` file. so i guest conflict will happen here.

**Comment by igorkasyanchuk** [comment]
"will happen"? or happening already?

**Comment by mkhairi** [comment]
happening already,  ```@import "font-awesome";``` loaded from ```gem 'font-awesome-rails'```  which is non sass version of font-awesome

**Comment by igorkasyanchuk** [comment]
I see, thanks

BTW maybe adding "font-awesome-sass/font-awesome", or something like that can help?

**Comment by mkhairi** [comment]
Yeah, load with extension can avoid this conflict  ```@import "font-awesome.scss";```.
Thanks.
