### ISSUE TITLE
uninitialized constant RailsDb::Database

### ISSUE THREAD

**Issue by binodmainali1** [igorkasyanchuk/rails_db#51]
Followed all the steps, running rails 3.2.X. But I am greeted with the following error all the time.

module RailsDb
  module ApplicationHelper
    include ::FontAwesome::Rails::IconHelper
    def rails_db_tables
      RailsDb::Database.accessible_tables
    end
    def link_to_add_fields(name, f, type)
      new_object = f.object.send "build_#{type}"
      id = "new_#{type}"

**Comment by igorkasyanchuk** [comment]
Hmm, not sure, I've specs with Rails 3.2 and they passed

when do you get this error? when app starts?

**Comment by binodmainali1** [comment]
visiting this URL http://localhost:3000/rails/db gives me that error.
