### ISSUE TITLE
Generating a URL from non sanitized request parameters is insecure!

### ISSUE THREAD

**Issue by adamshen** [igorkasyanchuk/rails_db#52]
In rails 5, it seems parameters need to be sanitized when we use then to generate urls.

**Comment by adamshen** [comment]
ActionView::Template::Error (Generating a URL from non sanitized request parameters is insecure!):
    73:         <% end %>
    74:         <% @model.column_names.each do |column| %>
    75:           <th class="column_<%= column %>" style="<%= display_style_column(@table.name, column)%>">
    76:             <%= sort_link @q, column, controller: :tables, action: :data %>
    77:           </th>
    78:         <% end %>
    79:       </tr>

**Comment by adamshen** [comment]
ActionView::Template::Error (Generating a URL from non sanitized request parameters is insecure!):
    73:         <% end %>
    74:         <% @model.column_names.each do |column| %>
    75:           <th class="column_<%= column %>" style="<%= display_style_column(@table.name, column)%>">
    76:             <%= sort_link @q, column, controller: :tables, action: :data %>
    77:           </th>
    78:         <% end %>
    79:       </tr>

**Comment by adamshen** [comment]
```
ActionView::Template::Error` (Generating a URL from non sanitized request parameters is insecure!):
    73:         <% end %>
    74:         <% @model.column_names.each do |column| %>
    75:           <th class="column_<%= column %>" style="<%= display_style_column(@table.name, column)%>">
    76:             <%= sort_link @q, column, controller: :tables, action: :data %>
    77:           </th>
    78:         <% end %>
    79:       </tr>
  ```

**Comment by igorkasyanchuk** [comment]
@adamshen could you please make a PR with fix?

**Comment by igorkasyanchuk** [comment]
try now
