### ISSUE TITLE
Database Config

### ISSUE THREAD

**Issue by Gbarnett374** [igorkasyanchuk/rails_db#61]
This gem is great. I was wondering if there is a way to use a specific database config for the Gem (instead of the config that Rails chooses based on the environment)?

 I want to use this in my production rails app but have it either use a read-only user or a read replica database.

**Comment by igorkasyanchuk** [comment]
right now this feature doesn't exists. maybe you should try to use standalone version and maybe you can manage how to specify different Yaml file with DB configuration? (I just physically don't have time to work on this now)

Idea with having second application with read-only user seems to be OK. You can deploy just blank app but with read-only user.
