### ISSUE TITLE
Invalid CSS in Production

### ISSUE THREAD

**Issue by augustosamame** [igorkasyanchuk/rails_db#64]
Hi. When using Capistrano to deploy my app, I get the following error during asset precompile:

```
, [2016-11-24T04:02:26.062183 #3833]  INFO -- : Writing /home/deploy/gaaf/releases/20161124040120/public/assets/rails_db/vendor/placeholder-a6bf649f3ba721aef7eaf1ffe17c76a9a3794add0c8e70998ff59da9e1b327bf.js.gz
rake aborted!
Sass::SyntaxError: Invalid CSS after "...kground-image: ": expected expression (e.g. 1px, bold), was "<%= asset_path(..."
(sass):29
```

I am using:

rails 5.0.0.1
sass-rails (5.0.6)
sprockets-rails (3.2.0)

removing the gem from production resolves the issue, but I would really like to use it in production.

**Comment by igorkasyanchuk** [comment]
shoud be fixed with latest version
