### ISSUE TITLE
Support postgresql schemas

### ISSUE THREAD

**Issue by andrecavallari** [igorkasyanchuk/rails_db#67]
You could improve the support for Postgresql schemas, in one of my applications I have some additional schemas, but cant change schemas in your plugin...

And wow, very nice plugin for Rails!

**Comment by igorkasyanchuk** [comment]
@andrecavallari thanks, it might be interesting, but unfortunately we need a volunteer to do this. I'm a bit busy. Maybe you can code it by yourself and just create PR

**Comment by MicFin** [comment]
Does Postgresql not work at all?

**Comment by igorkasyanchuk** [comment]
Postgres works
