### ISSUE TITLE
Invalid css error when importing foundation

### ISSUE THREAD

**Issue by Typpex** [igorkasyanchuk/rails_db#7]
Hi,
I just tried to install rails db, put rails_db in my gemfile under development group, executed bundle install but when i visit the page here is the error i got: 
Invalid CSS after "...ules: $modules ": expected "}", was "!global;"
  (in /Users/romainverbeke/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rails_db-0.2.1/app/assets/stylesheets/rails_db/foundation_and_overrides.css.scss:13)

My bundle install show the following for foundation and sass:
Using foundation-rails 5.5.0.0
Using sass 3.2.19
Using sass-rails 4.0.5

**Comment by ILoGM** [comment]
The same was for me until I update sass-rails. Try it

**Comment by Typpex** [comment]
@ILoGM I confirm it's working :) i thought i had the latest already ><

**Comment by itsjms** [comment]
Sass needs to be on version 3.2.19 as well. I updated sass-rails to 4.0.5 with sass version 2.2.2 and still doesn't work.

**Comment by igorkasyanchuk** [comment]
it's always good to upgrade your gems :) sometimes it can be painful but I hope not with this gem
