### ISSUE TITLE
Rails 3.2 Sass method argument error

### ISSUE THREAD

**Issue by spacewaffle** [igorkasyanchuk/rails_db#70]
After installing and heading to localhost:3000/rails/db I get a syntax error in a gem scss file

`wrong number of arguments (given 1, expected 2) for 'asset-path'
  (in /Users/Blah/.rvm/gems/ruby-2.3.0/gems/rails_db-1.4.1/app/assets/stylesheets/rails_db/app.scss)`

Looking at the gem, asset-path is written like so:

`table.custom_sorting th .asc {
  background-image: asset-path('rails_db/up_arrow.gif');
}`

For 3.2 support, we'd need a branch that changes this to 
`table.custom_sorting th .asc {
  background-image: asset-path('rails_db/up_arrow.gif', 'image');
}`

**Comment by igorkasyanchuk** [comment]
please create a PR and travis will run all tests, if it's ok I'll merge to master. thanks

**Comment by spacewaffle** [comment]
I took a quick look at the codebase and that .custom_sorting class isn't referenced anywhere else but that css file. Is it possible that's old css that isn't being used anymore?

**Comment by igorkasyanchuk** [comment]
you know you are absolutely right 👍 
it was an old code. you can remove it :) I think you can also remove "arrows" images too

**Comment by igorkasyanchuk** [comment]
fixed
