### ISSUE TITLE
undefined method `assets'

### ISSUE THREAD

**Issue by mak1966** [igorkasyanchuk/rails_db#71]
Hi, 
I am new to ROR

I used rails_db in other project and it works fine, however the gem reporting the following error:

/usr/local/rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x0000000431c9d8> (NoMethodError)

Note that I am using ruby 2.3 and rails 5.0.1 
I am building and API Back-End
rails new <app_name> --api

Thanks

**Comment by igorkasyanchuk** [comment]
without assets it won't work.
because gem in required to have assets to build the UI
