### ISSUE TITLE
Rails 3.2 no attr_accessible support breaks creates and updates

### ISSUE THREAD

**Issue by spacewaffle** [igorkasyanchuk/rails_db#72]
I found that when creating or updating records, no parameters get inserted because attr_accessor doesn't exist on the created classes. This is due to the gem supporting Rails 4 strong parameters but not the old Rails 3 attr_accessible way.

**Comment by igorkasyanchuk** [comment]
good catch too ...
could you please make a PR with this fix? for Rails < 4 ?

**Comment by igorkasyanchuk** [comment]
done
