### ISSUE TITLE
Importing error from CSV file

### ISSUE THREAD

**Issue by shivabhusal** [igorkasyanchuk/rails_db#80]
I exported a table from the remote MS-SQL database using Rails-DB 'export' link. It exported data in `.csv` format. Then I tried to import the csv file to the same app using local MSSQL database then I got this error.

```sql
Error occurred during import: TinyTds::Error: Incorrect syntax near ','.: id,username,username_canonical,email,email_canonical,enabled,salt,last_login,confirmation_token,password_requested_at,roles,uuid,first_name...
```

## Expectation
Since I exported the data using the same app i.e. RailsDB it should be able to import the data without any error.

**Comment by igorkasyanchuk** [comment]
I'm closing this, it's old and actually I not able to add full support for MS-SQL
