### ISSUE TITLE
View Customization

### ISSUE THREAD

**Issue by katsuya0515** [igorkasyanchuk/rails_db#81]
First of all, thanks for your great work. This is really useful.
One quick question, Is it possible to customize the views?

**Comment by igorkasyanchuk** [comment]
Thanks)
Depends on your needs. It's possible. Just to place erb  in same location as in gem I guess. This is something what also can be added to gem in future

**Comment by katsuya0515** [comment]
Thanks! If I end up implementing this, I'll commit it here
