### ISSUE TITLE
rails_db not compatible with simple_form 4.1.0

### ISSUE THREAD

**Issue by wrburgess** [igorkasyanchuk/rails_db#94]
`gem "simple_form", "4.1.0"`
`gem "rails_db", "2.0.4"`

```
Bundler could not find compatible versions for gem "simple_form":
  In Gemfile:
    simple_form (= 4.1.0)

    rails_db (= 2.0.4) was resolved to 2.0.4, which depends on
      simple_form (~> 4.0.1)
```

**Comment by igorkasyanchuk** [comment]
for now pls try "master" branch

I did this modification
https://github.com/igorkasyanchuk/rails_db/commit/32b50949a5687a3a47a79f43d6a9066c03736152

If it works - I'll release a new version very soon

**Comment by wrburgess** [comment]
This change worked for me. Thanks, @igorkasyanchuk !

**Comment by igorkasyanchuk** [comment]
try newer version 2.0.5
