### ISSUE TITLE
Add Support for Rails 6

### ISSUE THREAD

**Issue by addisonmartin** [igorkasyanchuk/rails_db#99]
When installing this gem in a Ruby on Rails 6.0 application, it breaks the entire application.
The following error is thrown when attempting to visit any page:

Sprockets::FileNotFound couldn't find file 'codemirror/modes/sql' with type 'application/javascript'

I suspect this has something to do with Rails 6 using webpacker by default.

**Comment by igorkasyanchuk** [comment]
Try new version "2.1.0"

**Comment by addisonmartin** [comment]
Hi, thank you for your response. The issue is still not fixed when using version 2.1.0. The new error is similar, but different:

Sprockets::FileNotFound couldn't find file 'javascripts/codemirror' with type 'application/javascript'

This occurs in application.html.erb at the stylesheet link tag:   <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

**Comment by igorkasyanchuk** [comment]
@addisonmartin what about rails_db-2.1.1.gem ?

**Comment by addisonmartin** [comment]
Version 2.1.1 fixed it. Thank you!
